export const TECH_KEYWORDS = [
  "code",
  "coding",
  "program",
  "programming",
  "developer",
  "debug",
  "bug",
  "api",
  "backend",
  "frontend",
  "database",
  "sql",
  "nosql",
  "software",
  "develop",
  "development",
  "app",
  "application",
  "website",
  "web",
  "mobile",
  "beginner",
  "learn",
  "learning",
  "framework",
  "javascript",
  "typescript",
  "python",
  "java",
  "c++",
  "golang",
  "rust",
  "react",
  "next",
  "node",
  "express",
  "docker",
  "kubernetes",
  "cloud",
  "aws",
  "azure",
  "gcp",
  "machine learning",
  "ai",
  "llm",
  "model",
  "algorithm",
  "data structure",
  "git",
  "github",
  "devops",
  "security",
  "hackathon",
  "prototype",
  "pitch",
  "mvp",
  "sprint",
  "roadmap",
  "deployment",
  "redis",
  "cache",
  "latency",
  "concurrency",
  "thread",
  "node.js",
  "node",
];

export const IRRELEVANT_WORDS = [
  "mountain",
  "elevation",
  "beachfront",
  "shore",
  "sea",
  "altitude",
];

export const PARAG_SYSTEM_PROMPT = [
  "You are MAHORAGA, a concise and highly adaptive assistant for technology, architecture, and engineering execution.",
  "Answer within software engineering, product prototyping, and technical execution.",
  "If the user asks outside those domains, politely redirect to technical topics.",
  "Keep responses practical, actionable, and under 120 words unless detail is explicitly requested.",
  "Do NOT use any emojis or emoticons in your responses under any circumstances. Keep responses in plain text.",
].join(" ");

export function getDomainRestrictionReply(): string {
  return [
    "I can help with technology, engineering, and architecture topics.",
    "Try asking about coding, architecture, APIs, debugging, MVP planning, or systems design.",
    "Example: !How do I design a scalable backend project with Node and Redis?",
  ].join("\n");
}

export const PARAG_HELP_TEXT = [
  "MAHORAGA - Adaptive Technology and Engineering Assistant",
  "Available Commands:",
  "\u2022 !help - Show this help",
  "\u2022 !hello - Check bot availability",
  "\u2022 !reset - Reset your conversation context",
  "\u2022 !<question> - Chat directly with MAHORAGA (e.g. !How do I optimize API latency?)",
].join("\n");
